#cloud-config
hostname: smol-metal
disable_root: false
network:
  config: disabled
users:
  - name: friend
    groups: users, admin, docker, sudo, kvm
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: true
    ssh_import_id:
      - gh:cloudymax
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC3xEankn5zUklqZ5XVRbjP9XrXmK49VZ4OJqkzRF5JJpolBAwmJIUoww6G51g9IlYWzzijtfRSsQxoZHmHp+sSz/qP5zbjoFVCJ08N0ulqb8okM5C7+uET3dZKxwMT6DLFKSLebYnFlCtbp6VnDvp6gP+ZIesL6cxVWC/fSjTbyesEaNWkigI+2zF3sSDOvrSGvRmQSOfOvdjAY8xvcKkwj4uSXa5qsVM7OX+j+2vARredbvya6YyAkumB9SXVHqnFdOOo1jgMtdNGFPi703dgAnfQp7yafR9Ext46pkO8zcyroysogKjI0HqLqUtV6tAG7NZo4+u8k9uYkZmQa26u2rmkx6kUP1jaDfrSp/33dcCLRVKd/FOiv5Ztwvl71fKh3az9khf/ZxFO2thDy8M0TY46TWs87eow8McNmOJWvsyuvVsI7ZyRhGWQkx7V0vpsd8ClDf91enKt4tBDlTu8PYvI2i2UMCeFb+uSt4c2D/kjTCM/+XPrljLupIfs7pM= max
package_update: true
package_upgrade: true
packages: 
  - wireguard
  - openresolv
  - ssh-import-id
  - sudo
  - curl
  - tmux
  - netplan.io
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - htop
  - iotop
  - git-extras
  - rsyslog
  - fail2ban
  - gpg
  - open-iscsi
  - nfs-common
  - ncdu
runcmd:
  #####################
  # Import SSH keys
  - sudo -u friend ssh-import-id-gh cloudymax  
  - sudo -u friend ssh-import-id-gh jessebot
  ######################
  # Install YQ
  - wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq &&\
  - chmod +x /usr/bin/yq
  ######################
  # Install Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - sudo apt-get update 
  - sudo apt-get install -y docker-ce
  ########################
  # Install Docker Compose
  - sudo -u friend -i mkdir -p /home/friend/.docker/cli-plugins/
  - sudo -u friend -i curl -SL https://github.com/docker/compose/releases/download/v2.17.3/docker-compose-linux-x86_64 -o  /home/friend/.docker/cli-plugins/docker-compose
  - sudo chmod +x /home/friend/.docker/cli-plugins/docker-compose
  ########################
  # Brew and Python3
  - wget https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
  - chmod +x /install.sh
  - chmod 777 /install.sh
  - sudo -u friend NONINTERACTIVE=1 /bin/bash /install.sh
  - sudo -u friend /home/linuxbrew/.linuxbrew/bin/brew shellenv >> /home/friend/.profile
  - sudo -u friend /home/linuxbrew/.linuxbrew/opt/python@3.11/libexec/bin >> /home/friend/.profile
  - sudo -u friend /home/linuxbrew/.linuxbrew/bin/brew install python@3.11 bitwarden-cli b2-tools k9s neovim
  - sudo -u friend /home/linuxbrew/.linuxbrew/bin/pip3.11 install smol-k8s-lab onboardme
  - sudo mkdir -p /home/friend/.config/smol-ka8s-lab
  - sudo chown -R friend:friend /home/linuxbrew
  - sudo chown -R friend:friend /home/friend
  ########################
  # Start system services
  - systemctl daemon-reload
  - sudo systemctl enable fail2ban
  - sudo systemctl start fail2ban
