#cloud-config
hostname: ${HOSTNAME}
disable_root: false
network:
  config: disabled
users:
  - name: ${USERNAME}
    groups: users, admin, docker, sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: "$6$rounds=4096$saltsaltlettuce$Lp/FV.2oOgew7GbM6Nr8KMGMBn7iFM0x9ZwLqtx9Y4QJmKvfcnS.2zx4MKmymCPQGpHS7gqYOiqWjvdCIV2uN."
bootcmd:
 - test -z "$(blkid /dev/nvme1n1)" && mkfs -t ext4 -L data /dev/nvme1n1
 - mkdir -p /data
 - mkdir -p /home/${USERNAME}/.aws
 - sudo apt-get update
 - sudo apt-get install -y ssh-import-id
 - sudo -u ${USERNAME} ssh-import-id-gh ${GITHUB_USERNAME}
mounts:
 - [ "/dev/nvme1n1", "/data", "ext4", "defaults,nofail", "0", "2" ]
write_files:
- path: /etc/modprobe.d/blacklist.conf
  content: |
    blacklist vga16fb
    blacklist nouveau
    blacklist rivafb
    blacklist nvidiafb
    blacklist rivatv
- path: /home/${USERNAME}/.aws/credentials
  content: |
    [default]
    aws_access_key_id = ${AWS_ACCESS_KEY_ID}
    aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}
- path: /home/${USERNAME}/.aws/config
  content: |
    [default]
    region = ${REGION}
    output = json
package_update: true
package_upgrade: true
packages: 
  - wireguard
  - openresolv
  - ssh-import-id
  - sudo
  - curl
  - tmux
  - netplan.io
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - htop
  - iotop
  - git-extras
  - rsyslog
  - fail2ban
  - gpg
  - open-iscsi
  - nfs-common
  - ncdu
  - nvtop
  - linux-headers-generic
  - gcc
  - kmod
  - make
  - pkg-config
  - libvulkan1
  - rsync
  - zip
runcmd:
  - mkdir -p /data/var
  - mkdir -p /data/usr
  - mkdir -p /data/home
  - rsync -avz /var/ /data/var
  - rsync -avz /usr/ /data/usr
  - rsync -avz /home/ /data/home
  - mount -o bind /data/var /var
  - mount -o bind /data/usr /usr
  - mount -o bind /data/home /home
  ######################
  # Install YQ
  - wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq &&\
  - chmod +x /usr/bin/yq
  ######################
  # Install Docker
  - sudo chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - sudo apt-get update 
  - sudo apt-get install -y docker-ce
  ########################
  # Install Docker Compose
  - sudo -u ${USERNAME} -i mkdir -p /home/${USERNAME}/.docker/cli-plugins/
  - sudo -u ${USERNAME} -i curl -SL https://github.com/docker/compose/releases/download/v2.17.3/docker-compose-linux-x86_64 -o  /home/${USERNAME}/.docker/cli-plugins/docker-compose
  - sudo chmod +x /home/${USERNAME}/.docker/cli-plugins/docker-compose
  ########################
  # Brew and Python3
  - wget https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
  - chmod +x /install.sh
  - chmod 777 /install.sh
  - sudo -u ${USERNAME} NONINTERACTIVE=1 /bin/bash /install.sh
  - sudo -u ${USERNAME} /home/linuxbrew/.linuxbrew/bin/brew shellenv >> /home/${USERNAME}/.profile
  - sudo -u ${USERNAME} /home/linuxbrew/.linuxbrew/opt/python@3.11/libexec/bin >> /home/${USERNAME}/.profile
  - sudo -u ${USERNAME} /home/linuxbrew/.linuxbrew/bin/brew install python@3.11 neovim
  - sudo chown -R ${USERNAME}:${USERNAME} /home/linuxbrew
  - sudo chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}
  ########################
  # Start system services
  - systemctl daemon-reload
  - sudo systemctl enable fail2ban
  - sudo systemctl start fail2ban
  ########################
  # AWS CLI
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
  ########################
  # Nvidia driver
  - wget curl https://raw.githubusercontent.com/GoogleCloudPlatform/compute-gpu-installation/main/linux/install_gpu_driver.py -O install_gpu_driver.py
  - python3 install_gpu_driver.py
  ########################
  # Container Runtime
  - |
    distribution=$(. /etc/os-release;echo $ID$VERSION_ID) && \
    curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg && \
    curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list | \
      sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
      sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
  - apt-get update
  - apt-get install -y nvidia-container-toolkit
  - nvidia-ctk runtime configure --runtime=docker --set-as-default
  - systemctl restart docker
