name: Run Terraform
on: 
  workflow_dispatch:
    inputs:
      vm_sku:
        description: 'Virtual Machine SKU'
        required: true
        default: 't3.xlarge'
      max_bid:
        description: 'Maximum spot bid amount'
        required: true
        default: '0.24'

jobs:
  terraform:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Terraform fmt
      id: fmt
      run: |
        docker run --platform linux/amd64 \
          -v $(pwd):/terraform -w /terraform \
          hashicorp/terraform fmt
      continue-on-error: false
      shell: bash

    - name: Terraform Init
      id: init
      run: |
        docker run --platform linux/amd64 \
          -e "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -e "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -v $(pwd):/terraform -w /terraform hashicorp/terraform init -upgrade
      continue-on-error: false
      shell: bash
      
    - name: Terraform Validate
      id: validate
      run: |
        docker run --platform linux/amd64 \
          -v $(pwd):/terraform -w /terraform \
          hashicorp/terraform validate -no-color
      continue-on-error: false
      shell: bash

    - name: Terraform Plan
      id: plan
      run: |
        docker run --platform linux/amd64 \
          -e "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -e "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -v $(pwd):/terraform -w /terraform \
          -var="ec2_instance_type=$VM_SKU" \
          -var="max_spot_price=$MAX_BID" \
          hashicorp/terraform plan
      continue-on-error: false
      shell: bash
      env:
        VM_SKU: ${{ github.event.inputs.vm_sku }}
        MAX_BID: ${{ github.event.inputs.max_bid }}

    - name: Terraform Apply
      id: apply
      run: |
        docker run --platform linux/amd64 \
          -e "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -e "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -v $(pwd):/terraform -w /terraform \
          hashicorp/terraform apply \
          -var="ec2_instance_type=$VM_SKU" \
          -var="max_spot_price=$MAX_BID" \
          -no-color -auto-approve -input=false
      continue-on-error: false
      shell: bash
      env:
        VM_SKU: ${{ github.event.inputs.vm_sku }}
        MAX_BID: ${{ github.event.inputs.max_bid }}
